### ISSUE TITLE
On Startup: open /.../sessions/1607366498.json: no such file or directory

### ISSUE THREAD

**Issue by myisaak** [gumieri/sway-session#1]
When trying to save the session by running `sway-session save`, I receive the following error:

```
open /home/stromae/.local/share/sway-session/sessions/1607366498.json: no such file or directory
```

I am on Arch Linux x64 with a go version 1.15.5.

**Comment by gumieri** [comment]
Hi there.

has been a while that I don't check this project. But, if you want to make it work, it seems the problem to be that the directory does not exist. It may work if you run `mkdir -p ~/.local/share/sway-session/sessions`.

Let me know if it worked. I will check the code to fix later.

Thank you.

**Comment by myisaak** [comment]
Thanks. It fixed the first issue but unfortunately now I get `PID not found`

**Comment by myisaak** [comment]
Ok after a system upgrade and a restart it works.
